// A short lesson for each of the 52 weeks, plus a few for the weeks before the last jab and one a month in year two.
// General guidance in Steadie's voice: kind, plain, never about medication doses. Each has a title, a two-word week
// name for the Plan screen, a one-line blurb, two short paragraphs and two things to try. Land is weeks 1 to 8,
// Settle 9 to 26, Steady 27 to 52.

export interface Lesson { title: string; week: string; blurb: string; paras: [string, string]; tries: [string, string] }

const L = (title: string, week: string, blurb: string, p1: string, p2: string, t1: string, t2: string): Lesson =>
  ({ title, week, blurb, paras: [p1, p2], tries: [t1, t2] });

export const WEEKLY_LESSONS: Lesson[] = [
  // Land: weeks 1 to 8
  L("Why protein matters more now", "Protein first", "As appetite returns, building meals around protein keeps you fuller and protects muscle.",
    "As your appetite comes back, meals built around protein tend to keep you fuller for longer, so hunger feels easier to handle.",
    "Protein also helps your body hold on to muscle. Muscle is part of what you worked for, and strength sessions plus protein help you keep it.",
    "A palm-sized portion at each meal: eggs, Greek yoghurt, chicken, fish, tofu, beans or lentils.", "Start with breakfast. It's the meal most people miss."),
  L("Hunger is coming back, and that's expected", "Hunger returns", "Appetite returning is your body working as it should. A plan for it makes it easier.",
    "Many people notice hunger creeping back in the first weeks. It isn't a sign anything has gone wrong. It's biology, and it's why this year has a plan.",
    "Knowing your hungriest time of day lets you get ahead of it, with a meal or snack that's ready before the hunger is.",
    "Notice when hunger is strongest this week. You told us your hungry times; check if they're right.", "Have one protein snack ready for that time, like yoghurt or a boiled egg."),
  L("Strength is the quiet win", "Get stronger", "Two short sessions a week help you keep muscle, and muscle helps you stay steady.",
    "Strength work isn't about the gym. Standing up from a chair, carrying shopping and climbing stairs are all strength, and they get easier with practice.",
    "Two sessions of about 25 minutes a week is plenty. Stopping a couple of reps before it gets too hard is exactly right.",
    "Do both sessions this week, even if one is short.", "Pick the easier version of any move without a second thought."),
  L("Drinks count too", "Water first", "Thirst can feel like hunger. A glass of water is an easy first check.",
    "It's easy to mistake thirst for hunger, especially in the afternoon. A glass of water won't fix real hunger, but it can tell you which one you've got.",
    "Fizzy drinks and juices can add up without filling you. Water, tea, coffee and sugar-free drinks are all fine choices.",
    "Have a glass of water before dinner while you cook.", "Keep a bottle where you'll see it at work or at home."),
  L("The 10-minute pause", "Pause and choose", "Waiting ten minutes before seconds gives fullness time to catch up.",
    "Feeling full takes a little while to arrive after eating. A short pause before a second helping lets you notice how full you actually are.",
    "This isn't a rule to never have seconds. It's a moment to decide, rather than to go on autopilot.",
    "Plate up once, and wait ten minutes before deciding on more.", "Put the serving dish back in the kitchen, not on the table."),
  L("Your steady zone", "Weight, calmly", "Day-to-day weight jumps around. The 7-day average tells the real story.",
    "Weight can move by a kilo or more between mornings, mostly from water, salt, sleep and your cycle. None of that is fat, and none of it needs a reaction.",
    "Your steady zone is a small range above your lowest weight. While the 7-day average sits in it, you're holding steady.",
    "Weigh in at the same time a few mornings a week, if you're comfortable to.", "Look at the trend line, not the number on any one day."),
  L("Sleep and appetite", "Rest well", "Short nights can turn up hunger the next day. Better sleep makes everything easier.",
    "After a short night, many people feel hungrier and reach for quick energy. It's a common pattern, and your check-ins may show it for you too.",
    "You don't need perfect sleep. A steadier bedtime and a wind-down without screens often help more than anything else.",
    "Pick a bedtime and keep it on five nights this week.", "Leave your phone outside the bedroom for one night and see how it feels."),
  L("Walking does more than you think", "Keep moving", "Steps add up across the day and help keep weight steady over time.",
    "Strength sessions build muscle; everyday movement does the steady work in between. Walking is the simplest way to get more of it.",
    "It doesn't need to be a big walk. Ten minutes after a meal, a longer way round, or a call taken on foot all count.",
    "Take a 10-minute walk after dinner on three days.", "Check your steps on one day this week, just to know your starting point."),

  // Settle: weeks 9 to 26
  L("Meals that hold you steady", "A rhythm for meals", "Regular meals with protein and fibre make hunger easier to predict and plan around.",
    "In Settle, regular meals do a lot of quiet work. When you know roughly when you'll next eat, hunger is easier to sit with.",
    "Structure is not a rule book. It's a rough rhythm you can bend for a meal out or a busy day.",
    "Three meals at roughly the same times on five days this week.", "Have a plan for the hungriest time of day, like a protein snack ready to go."),
  L("Fibre, a little at a time", "More fibre", "Fibre keeps you fuller and helps digestion. Building it up slowly is kinder to your stomach.",
    "Beans, lentils, oats, wholegrains, fruit and vegetables all add fibre. Your meal plan adds a little more each week.",
    "Going up gradually, with plenty to drink, gives your gut time to adjust.",
    "Add a handful of beans or lentils to one meal.", "Swap one white bread or pasta for a wholegrain one."),
  L("A plan beats tired decisions", "Plan the week", "Ten minutes on Sunday saves a lot of tired decisions on a Wednesday.",
    "Most food decisions happen when we're tired or busy. A plan made earlier, when you're calm, does the deciding for you.",
    "Your meal plan and shopping list are there for exactly this. A plan you change halfway through still did its job.",
    "Pick next week's meals before Sunday evening.", "Do one shop from the list, and tick it off as you go."),
  L("Eating out without worry", "Eating out", "One meal out never undoes a steady week. A little thought beforehand helps.",
    "Meals out are part of life, and they belong in your plan. Looking at the menu before you go makes choosing easier.",
    "A protein-first main, a side of veg, and eating slowly enough to enjoy it is plenty. Then the next meal is just the next meal.",
    "Look at the menu before your next meal out.", "Choose your main first, then decide on extras."),
  L("Cravings come and go", "Riding cravings", "A craving tends to rise and fall like a wave. You can let it pass, or have a little on purpose.",
    "Cravings are normal and they usually ease within 15 to 20 minutes, especially if you do something else in the meantime.",
    "If you decide to have the thing, have a portion on a plate, sit down and enjoy it. Planned is very different from grazing.",
    "Next time a craving hits, set a 15-minute timer and do something else.", "If you still want it, have a set portion, sitting down."),
  L("The table matters", "Eat at the table", "Eating without screens helps you notice when you've had enough.",
    "When we eat in front of a screen, it's easy to finish the plate without noticing it. Sitting at a table brings the meal back into focus.",
    "It needn't be every meal. One screen-free meal a day is a good start.",
    "Eat one meal a day at the table with screens off.", "Put your fork down between mouthfuls for the first few minutes."),
  L("Weekends are different, and that's fine", "Weekend rhythm", "Weekends often look different. A loose plan keeps them enjoyable and steady.",
    "Later mornings, meals out and drinks can shift weekends. Rather than fighting that, plan around it.",
    "A protein breakfast, even a late one, and a walk at some point are two easy anchors.",
    "Plan one weekend meal in advance.", "Get outside for a walk on Saturday or Sunday."),
  L("Alcohol and appetite", "Drinks, honestly", "Drinks can lower your guard and raise your appetite. Knowing that helps you choose.",
    "Alcohol adds energy and can make food choices looser later in the evening. Your check-ins may already show a pattern after drinks.",
    "You don't have to stop. Alternating with water, eating first and deciding a number in advance all help.",
    "If you drink this week, have a glass of water between drinks.", "Eat a proper meal before you go out."),
  L("A third session", "Stronger still", "As the first sessions feel easier, an optional third one helps you keep building.",
    "By now the moves should feel more familiar. A third session a week is optional, and it's a good way to keep progressing.",
    "If the moves feel too easy, say so after a session and the next ones will step up.",
    "Try a third session this week, even a short one.", "Tell us how each session felt when you finish."),
  L("Stress and eating", "Under pressure", "Stress changes appetite for many people. Small, kind routines help more than strict rules.",
    "When life is stressful, routines often slip and comfort eating can creep in. That's human, and nothing to be hard on yourself about.",
    "Keeping one or two anchors, like protein at breakfast and a short walk, gives the week some shape when everything else is busy.",
    "On a stressful day, keep just one habit and let the rest go.", "Try five slow breaths before you eat when you're wound up."),
  L("Hunger signals", "Know your hunger", "Rating your hunger before you eat helps you match the meal to what you need.",
    "Your morning check-in asks how hungry you were. Noticing hunger in the moment, on the same 1 to 5 scale, is just as useful.",
    "Eating when you're around 2, quite hungry, and stopping around 4, satisfied, is a comfortable rhythm for many people.",
    "Before two meals this week, rate your hunger from 1 to 5.", "Stop at satisfied once, and notice how you feel an hour later."),
  L("Batch cooking", "Cook once", "Cooking once and eating twice makes busy nights easier.",
    "Leftovers are a gift to your future self. Several of your recipes are designed to make more than one meal.",
    "A portion in the fridge or freezer turns a tired evening into an easy one.",
    "Cook one batch recipe this week.", "Freeze a portion with the date on it."),
  L("Holidays and breaks", "Time away", "Holidays are for enjoying. Keeping one or two habits makes coming back easy.",
    "Breaks from routine are good for you. The trick is to keep a thread, so it's easy to pick back up afterwards.",
    "Walking more than usual on holiday often balances out the extra meals out.",
    "Before your next trip, pick the one habit you'll keep.", "Plan your first week back before you go."),
  L("Snacks with a purpose", "Smarter snacks", "A planned snack can stop a big hunger later. Protein makes it work harder.",
    "Snacks aren't the enemy. A planned snack between meals can stop you arriving at dinner ravenous.",
    "Pairing protein with fibre, like yoghurt with fruit or hummus with veg, tends to keep you going longer.",
    "Plan your snacks for two days this week.", "Swap one packet snack for a protein one."),
  L("Strength, step by step", "Progress gently", "Getting stronger means adding a little at a time, never rushing.",
    "Muscles get stronger when they're asked to do a little more than last time: one more rep, a slightly harder version or an extra set.",
    "Sessions will step up gradually. If a move ever hurts sharply, stop and use the easier version.",
    "Notice one move that feels easier than a month ago.", "Do one extra rep on your favourite move."),
  L("Family meals", "Eating together", "Your meals can work for everyone at the table, with small changes.",
    "Most of your recipes suit the whole household. Serving portions in the kitchen helps everyone eat the amount that suits them.",
    "Nobody needs a separate diet meal. Adding extra carbs or sides for others is easy.",
    "Cook one plan recipe for the whole household.", "Plate up in the kitchen for one family meal."),
  L("When things shift", "Reset, kindly", "If your trend drifts up, a lighter reset week brings things back without drama.",
    "Your 7-day average may drift above your steady zone at some point. That's common, and it's the reason the zone exists.",
    "A reset week means going back to the basics that worked: protein first, regular meals, two sessions, more walking. Nothing extreme.",
    "If your trend is above the zone, pick two basics to focus on for one week.", "Check in with the coach if you'd like ideas."),
  L("Six months in", "Look back", "Settle ends this week. Take a moment to notice what's changed since you started.",
    "Habits that felt like effort a few months ago may now feel normal. That's the whole point of this year.",
    "Looking back at your check-ins and your trend can show you what works for you specifically.",
    "Read your 'what shapes your days' page.", "Write down the two habits that helped most."),

  // Steady: weeks 27 to 52
  L("Making it yours", "Your own routines", "The habits that stuck are now yours. Same steady ground, your way.",
    "By now, the habits that worked are yours. Steady is about keeping them in your own way.",
    "Every four weeks, Today offers a short look back at your month. If things shift, a reset week is always there.",
    "Pick the two habits that matter most to you and keep them.", "When your month's look back appears, give it two minutes."),
  L("Your own rules", "Personal rules", "A few simple rules of your own beat any diet plan.",
    "Rules like 'protein at breakfast' or 'walk after dinner' work because they're yours and they're easy to follow.",
    "Write them down. Three is plenty.",
    "Write down your three rules.", "Check one week against them, without judging."),
  L("Strength for life", "Keep lifting", "Once built, strength holds with one or two sessions a week.",
    "You've built a habit many people never manage. Keeping it going needs less effort than building it did.",
    "Even one session a week at the same effort keeps most of what you've gained.",
    "Keep at least one session in every week this month.", "Try a harder version of one move."),
  L("Seasons change", "Through the year", "Routines shift with the seasons. Adjusting them keeps you steady.",
    "Darker evenings, holidays and busy months all change how a week looks. Expect it, and adjust.",
    "An indoor walk, a different session time or simpler meals can keep the thread going.",
    "Think about what next month will look like.", "Adjust one routine to fit it."),
  L("Eating with others", "Social eating", "Food is social. You can enjoy it fully and still feel steady.",
    "Parties, celebrations and meals with friends are part of a good life. They don't need managing so much as enjoying.",
    "Eating your usual way the next morning is all it takes to carry on.",
    "Say yes to a meal out this month.", "Have your usual breakfast the next day."),
  L("Noticing drift early", "Early signals", "Small changes are easier to steer than big ones.",
    "Your trend, your check-ins and how your clothes feel are all early signals. Noticing them early means small adjustments are enough.",
    "If you notice a drift, it isn't something to worry about. It's information.",
    "Look at your trend once this week.", "If it's drifting, pick one basic to focus on."),
  L("Comfort without food", "Other comforts", "Having comfort that isn't food makes hard days easier.",
    "Food is a natural comfort, and it's fine sometimes. Having other comforts ready gives you a choice.",
    "A walk, a bath, a call with a friend or ten minutes outside can all shift a mood.",
    "Write a short list of non-food comforts.", "Try one on your next hard day."),
  L("The long view", "Big picture", "This year is about the next ten. Steady beats perfect.",
    "What you're building is a way of living, not a project with an end date. Steady, imperfect weeks add up.",
    "A wobbly week is just a week. The trend over months is what counts.",
    "Look at your trend over the last three months.", "Notice one thing that's easier now."),
  L("Fuelling your activity", "Food for movement", "Eating enough protein around activity helps your body recover.",
    "If you're moving more, your body needs fuel to recover and stay strong. A protein-rich meal or snack after a session helps.",
    "Under-eating can leave you tired and hungry later, which makes everything harder.",
    "Have a protein snack after one session this week.", "Notice how you feel the next day."),
  L("Sleep, revisited", "Better nights", "Good sleep still underpins everything. Small tweaks keep it on track.",
    "Your check-ins may show how sleep affects your hunger and energy. Few things help as much as a steady bedtime.",
    "A cool, dark room and a wind-down routine make a real difference over time.",
    "Keep the same bedtime for a week.", "Swap screen time for reading for the last half hour."),
  L("Cooking confidence", "Cook freely", "You know the basics now. Cooking without a recipe is the next step.",
    "Protein, veg, something filling and a sauce: that's most good meals. You can now put them together your way.",
    "The recipes are still there whenever you want them.",
    "Make one meal without a recipe this week.", "Try a cuisine you haven't cooked before."),
  L("Moving more, your way", "Find your movement", "The best activity is the one you'll keep doing.",
    "Swimming, dancing, cycling, gardening or classes all count. Enjoying it matters more than what it is.",
    "Adding one thing you enjoy makes staying active feel less like a task.",
    "Try a new kind of activity this month.", "Book it in like an appointment."),
  L("Talking to your GP", "Health checks", "Regular check-ups are part of looking after yourself this year.",
    "Your GP or practice nurse can check things like blood pressure and bloods. Your summary from Progress can help that conversation.",
    "Any questions about medication are always for your prescriber.",
    "Make your summary from Progress before your next appointment.", "Write down questions before you go."),
  L("Being kind to yourself", "Self-kindness", "Talking to yourself like a friend helps more than being strict.",
    "Harsh self-talk tends to make hard days harder. Kindness isn't letting yourself off; it makes it easier to carry on.",
    "When something doesn't go to plan, ask what a friend would say to you.",
    "Notice one harsh thought this week and rephrase it.", "Write down one thing you did well."),
  L("Halfway through Steady", "Look back again", "Most of a year of steady habits is something to be proud of.",
    "Take a moment to look back at where you started and what you've kept.",
    "The habits that stuck are worth naming. They'll carry you through the months ahead.",
    "Read back through your 'what shapes your days' page.", "Pick one habit to recommit to."),
  L("Busy weeks", "When life is full", "On busy weeks, the minimum still counts.",
    "Some weeks there's no room for everything. Having a minimum version, like one session and protein at breakfast, keeps the thread.",
    "Doing the minimum on a busy week is a success, not a compromise.",
    "Decide your minimum week now.", "Use it the next time a week gets busy."),
  L("Mindful eating", "Slow down", "Eating more slowly helps you enjoy food and notice fullness.",
    "Slowing down gives fullness time to register and makes meals more satisfying.",
    "It can be as simple as putting your fork down between mouthfuls.",
    "Make one meal a day last at least 15 minutes.", "Notice the taste of the first three mouthfuls."),
  L("Keeping strength interesting", "Mix it up", "Changing things up keeps sessions fresh and your body adapting.",
    "Doing the same moves forever can get dull. Trying harder versions or new exercises keeps things interesting.",
    "Your demos in Settings let you choose who shows each move.",
    "Try a harder version of two moves.", "Change who demonstrates your moves for a fresh look."),
  L("Celebrations and occasions", "Special days", "Special days are for enjoying. Steady habits carry on afterwards.",
    "Birthdays, holidays and celebrations are worth enjoying fully, without guilt.",
    "Your routine is there to come back to the next day, and that's all it takes.",
    "Enjoy the next occasion without tracking anything.", "Go back to your usual routine the next morning."),
  L("Your support team", "Who helps you", "Telling the people around you what helps makes it easier.",
    "Friends and family usually want to help but don't know how. Telling them what's useful makes a real difference.",
    "It might be cooking together, walking together or simply not commenting on food.",
    "Tell one person what would help you.", "Plan one active thing with someone else."),
  L("When motivation dips", "Low-motivation days", "Habits carry you when motivation doesn't.",
    "Motivation comes and goes. Habits are what keep things going on the days it's low.",
    "Making things easy, like having food ready or sessions booked, means you need less motivation.",
    "Make one habit easier this week, by preparing ahead.", "On a low day, do the smallest version."),
  L("Food and feelings", "Feelings and food", "Noticing why you're eating helps you choose what you need.",
    "Sometimes we eat because we're hungry, and sometimes because we're tired, bored or sad. Both are human.",
    "Asking 'am I hungry?' before eating gives you a moment to choose.",
    "Ask yourself 'am I hungry?' before two snacks this week.", "If you're not, try a non-food comfort first."),
  L("The season ahead", "Season ahead", "Light, weather and the calendar all change a week. A little planning keeps it steady.",
    "Whatever the time of year, the next few months will bring their own changes: lighter or darker evenings, holidays, busy spells.",
    "Choosing activities and meals that suit the season makes the routine easier to keep, rather than fighting it.",
    "Plan one activity that suits the weather over the next month.", "Add a meal that suits the season to next week's plan."),
  L("Protein, still", "Protein habits", "Protein at each meal is still one of the simplest steady habits.",
    "It's easy for habits from the early months to fade. Protein at each meal is worth keeping, because it helps with fullness and muscle at any stage.",
    "A quick look at your meals this week will tell you whether it's still there.",
    "Check that each meal had some protein on three days this week.", "Restock your easy protein options: eggs, yoghurt, tinned fish or beans."),
  L("Almost a year", "Nearly there", "You're nearly a year in. Time to plan the next one.",
    "Look back at what's changed and what's stayed steady. That's a great base for the year ahead.",
    "After week 52 the plan gets lighter: year two has a new lesson each month, and the habits are yours to choose.",
    "Write down what you want to keep doing next year.", "Make your summary from Progress to remember the year."),
  L("Keep what you've worked for", "The year ahead", "A year of steady habits. The next one is yours.",
    "You've spent a year building routines that work for you. That's the hardest part done.",
    "Keep checking in, keep the habits that matter and use a reset week whenever you need one.",
    "Pick three habits for the year ahead.", "Set a monthly reminder to check your trend."),
];

/** The lesson for a plan week (1 to 52). */
export const lessonFor = (week: number): Lesson => WEEKLY_LESSONS[Math.max(1, Math.min(WEEKLY_LESSONS.length, week)) - 1];

// Getting ready: for the weeks before the last jab, in order from someone's first week.
export const PREP_LESSONS: Lesson[] = [
  L("Getting ready, gently", "Getting ready", "A few weeks before your last jab is a lovely time to set up habits, while appetite is still quiet.",
    "Habits are easier to start when nothing else is changing. These weeks are a chance to practise the basics before your appetite comes back.",
    "There's nothing to get right yet. Think of it as a gentle rehearsal for the months ahead.",
    "Tick off this week's habits on the days you can.", "Notice which one feels easiest, and start there."),
  L("Protein, before you need it", "Protein early", "Building meals around protein now makes it second nature by the time hunger returns.",
    "Protein helps meals feel filling and helps your body hold on to muscle. Getting used to it now means one less thing to learn later.",
    "It needn't be big portions. A little at each meal, like eggs, yoghurt, fish, tofu or beans, is a good start.",
    "Have some protein at breakfast on three days this week.", "Write down three protein foods you actually enjoy."),
  L("Strength basics", "First sessions", "Two short sessions a week help protect muscle. Starting now makes them routine.",
    "The first sessions are about learning the moves, not working hard. Stopping a couple of reps before it gets tough is exactly right.",
    "Muscle helps you feel strong in everyday life, and it's part of staying steady over the year.",
    "Do one session this week, even a short one.", "Pick the easier version of any move whenever you like."),
  L("Talking to your prescriber", "A good conversation", "Your prescriber knows your situation best. A few notes beforehand make the conversation easier.",
    "How and when to stop is a decision for you and your prescriber. They can explain what to expect and answer questions about your medication.",
    "It helps to say what you're planning around it: meals with protein, strength sessions and a routine you're building now.",
    "Write down any questions you'd like to ask before your next appointment.", "Make your summary from Progress to take with you, if it helps."),
  L("A plan for the week", "Plan ahead", "Ten minutes of planning saves a lot of tired decisions later.",
    "Most food decisions happen when we're busy or tired. A plan made when you're calm does the deciding for you.",
    "Your meal plan and shopping list are there for exactly this. A plan you change halfway through still did its job.",
    "Look through next week's meals and swap any you don't fancy.", "Do one shop from your list."),
  L("Know your hungry times", "Hungry times", "Knowing when hunger tends to arrive lets you get ahead of it.",
    "Many people find hunger comes back at the same times each day. Knowing yours means a meal or snack can be ready first.",
    "Your morning check-in will start to show patterns too, like how sleep or a busy day changes things.",
    "Notice the time of day you think about food most this week.", "Plan a protein snack for that time."),
  L("Sleep and routine", "Steady days", "Steady sleep and regular meals give the weeks ahead a calm shape.",
    "Short nights can turn up hunger the next day. A steadier bedtime is one of the kindest things you can do for the months ahead.",
    "Regular mealtimes help too. They don't need to be strict, just roughly the same most days.",
    "Pick a bedtime and keep it on five nights.", "Have your meals at roughly the same times for three days."),
  L("What the first weeks bring", "Looking ahead", "Knowing what's coming makes the first weeks after your last jab easier.",
    "As the jabs wear off, appetite often returns over a few weeks. It's expected, and it's what this year is planned around.",
    "The habits you've practised here, protein, strength and a plan, are the ones that help most. You've already started.",
    "Read back over your habits and pick the one you'll lean on most.", "Have easy protein foods in for your first week."),
];

/** One lesson a month in year two, each with three earlier lessons on the same theme for the weeks in between. */
export const YEAR_TWO_LESSONS: { lesson: Lesson; again: [number, number, number] }[] = [
  { again: [27, 28, 42], lesson: L("A lighter second year", "Year two", "The plan gets lighter now. The habits you've kept do the steady work.",
    "A year of practice means many habits now happen without much thought. Year two is about keeping the ones that matter, your way.",
    "There's a new lesson each month, and a look back every four weeks. In between, you'll see earlier lessons again as refreshers.",
    "Choose the habit you'd like in place of 'Your own routine'.", "Notice one habit that now happens without trying.") },
  { again: [1, 50, 22], lesson: L("Protein, a year on", "Protein still", "Protein at each meal is still one of the simplest habits to keep.",
    "Habits from the early months can quietly fade. Protein is worth keeping, because it helps with fullness and muscle at any stage.",
    "If it's slipped, start with the meal it's easiest at, often breakfast.",
    "Check that each meal had some protein on three days this week.", "Try one new protein food this month.") },
  { again: [3, 23, 44], lesson: L("Strength that lasts", "Keep lifting", "Strength holds well with regular sessions, even short ones.",
    "Once built, strength needs less to keep it. One or two sessions a week at a steady effort keeps most of what you've gained.",
    "Changing a move now and then keeps sessions interesting and your body adapting.",
    "Keep at least one session in every week this month.", "Try a harder version of one move.") },
  { again: [2, 19, 13], lesson: L("Hunger, a year on", "Know your hunger", "Hunger still comes and goes. You know your patterns better than ever.",
    "By now you've seen how sleep, stress and busy days change your appetite. That knowledge is one of the year's best results.",
    "Rating hunger before a meal is still a useful check when things feel louder than usual.",
    "Rate your hunger before two meals this week.", "Have a plan for your hungriest time of day.") },
  { again: [12, 31, 45], lesson: L("Occasions and meals out", "Eating out", "Meals out and celebrations belong in a steady life.",
    "A year in, you've had plenty of meals out and special days. Most of them simply became part of the routine.",
    "Enjoying the occasion, then having your usual breakfast the next day, is all it takes.",
    "Say yes to a meal out this month.", "Choose your main first, then decide on extras.") },
  { again: [7, 36, 4], lesson: L("Rest, revisited", "Rest well", "Sleep still shapes hunger and energy. Small tweaks keep it working.",
    "Your check-ins may show how much sleep matters for you. A steady bedtime remains one of the simplest habits to keep.",
    "A cool, dark room and a wind-down without screens make a difference over time.",
    "Keep the same bedtime for a week.", "Swap screen time for something calmer in the last half hour.") },
  { again: [8, 38, 35], lesson: L("Moving for the fun of it", "Find your movement", "The best activity is the one you look forward to.",
    "Walking, swimming, dancing, gardening or a class all count. Enjoying it is what keeps it going.",
    "Trying something new now and then keeps movement feeling fresh rather than a task.",
    "Try a new kind of activity this month.", "Book it in like an appointment.") },
  { again: [32, 25, 47], lesson: L("Steering early", "Early signals", "Small drifts are easy to steer when you notice them early.",
    "How your clothes feel, your check-ins and your routines are all early signals. Noticing them early means small changes are enough.",
    "A reset week, back to the basics that worked, is always there and never needs to be dramatic.",
    "Look back at your last month once this week.", "If something has drifted, pick one basic to focus on.") },
  { again: [11, 20, 37], lesson: L("Kitchen habits", "Cook simply", "A few kitchen habits make the steady choice the easy one.",
    "A planned week, a batch in the freezer and a few go-to meals take the effort out of busy evenings.",
    "You can cook without a recipe now: protein, veg, something filling and a sauce.",
    "Cook one batch recipe and freeze a portion.", "Make one meal without a recipe.") },
  { again: [18, 33, 48], lesson: L("Comfort and stress", "Under pressure", "Hard weeks happen. A short list of comforts makes them easier.",
    "Stress changes appetite for many people. Food is a natural comfort, and having other comforts ready gives you a choice.",
    "On a hard week, keeping one or two anchors is plenty.",
    "Write a short list of non-food comforts.", "On a stressful day, keep just one habit.") },
  { again: [46, 24, 16], lesson: L("The people around you", "Who helps you", "Friends and family can make steady habits easier.",
    "People close to you usually want to help but may not know how. Telling them what's useful makes a real difference.",
    "Cooking together, walking together or simply not commenting on food can all help.",
    "Tell one person what would help you.", "Plan one active thing with someone else.") },
  { again: [40, 34, 51], lesson: L("Another year ahead", "The year ahead", "Two years of steady habits. The next one is yours too.",
    "Look back at what's become easy and what still takes a little care. Both are worth knowing.",
    "Keep the habits that matter, use a reset week whenever you need one, and be kind to yourself on harder weeks.",
    "Pick three habits for the year ahead.", "Write down one thing that's easier than a year ago.") },
];

/** A lesson with a key for marking it read: "w12" for plan week 12, "r3" for the third getting-ready week, "y5" for a
 *  year-two week. Refreshers are earlier lessons shown again in year two. */
export interface LessonPick { key: string; lesson: Lesson; refresher: boolean }

/** The lesson for the nth week of getting ready (1 is their first), cycling if there are more weeks than lessons. */
export const prepLessonFor = (n: number): LessonPick => {
  const i = (Math.max(1, n) - 1) % PREP_LESSONS.length;
  return { key: `r${i + 1}`, lesson: PREP_LESSONS[i], refresher: false };
};

/** The lesson for the nth week of year two: a new one every four weeks, and earlier ones on its theme in between. */
export const yearTwoLessonFor = (n: number): LessonPick => {
  const k = Math.max(1, n) - 1, month = YEAR_TWO_LESSONS[Math.floor(k / 4) % YEAR_TWO_LESSONS.length], step = k % 4;
  if (step === 0) return { key: `y${Math.floor(k / 4) % YEAR_TWO_LESSONS.length + 1}`, lesson: month.lesson, refresher: false };
  const week = month.again[step - 1];
  return { key: `w${week}`, lesson: lessonFor(week), refresher: true };
};

/** The lesson for a plan week counted from the last jab: getting ready (0 or less), the 52 weeks, then year two. */
export const lessonForWeek = (week: number, prepWeek = 1): LessonPick =>
  week < 1 ? prepLessonFor(prepWeek) : week > 52 ? yearTwoLessonFor(week - 52) : { key: `w${week}`, lesson: lessonFor(week), refresher: false };

/** Finds a lesson by its key, for opening it again. */
export function lessonByKey(key: string): Lesson | null {
  const n = Number(key.slice(1));
  if (!Number.isInteger(n) || n < 1) return null;
  if (key[0] === "w") return WEEKLY_LESSONS[n - 1] ?? null;
  if (key[0] === "r") return PREP_LESSONS[n - 1] ?? null;
  if (key[0] === "y") return YEAR_TWO_LESSONS[n - 1]?.lesson ?? null;
  return null;
}
