// The meal library, v1 (plan §5.3; starting lists in docs/research/food.md §3). Every recipe is a DRAFT: nutrition
// comes from the approximate ingredient table, costs are estimates, and nobody has timed or signed off any of them.
// scripts/check.ts holds every recipe to the Easy standard (plan §5.2) before the dietitian and the cook see it.
import type { Collection, Cuisine, Kit, Line, Recipe, Slot } from "./types.ts";

const L = (i: string, g: number, optional = false): Line => (optional ? { i, g, optional } : { i, g });

interface Draft {
  name: string; blurb: string; serves?: number;
  /** Minutes: hands-on to the table, then waiting while it cooks (including any oven preheat the prep doesn't cover). */
  time: [number, number]; ahead?: string; kit: Kit[]; washUp: number;
  collections?: Collection[]; cuisine: Cuisine; cost: 1 | 2 | 3; spicy?: boolean;
  ingredients: Line[]; steps: string[]; only?: Record<string, string[]>;
  stepsFor?: Record<string, string[] | Record<number, string>>; nameFor?: Record<string, string>; fridgeDays: number; freezes?: boolean; storeCupboard?: string;
}
const r = (slot: Slot, id: string, { time: [active, wait], ...d }: Draft): Recipe => ({
  id, slot, serves: 1, collections: [], freezes: false, ...d,
  time: { active, wait }, handsOn: active, total: active + wait,
  review: { status: "draft" },
});

export const RECIPES: Recipe[] = [
  /* ---------- breakfast ---------- */
  r("breakfast", "yoghurt-bowl", {
    name: "Greek yoghurt bowl", blurb: "Yoghurt, berries, oats and seeds, with no cooking.",
    time: [2, 0], kit: ["none"], washUp: 2, collections: ["no-cook", "gentle", "on-the-go"], cuisine: "Mediterranean", cost: 1,
    ingredients: [L("greek-yoghurt", 200), L("berries", 80), L("oats", 30), L("seeds", 15)],
    steps: ["Spoon the yoghurt into a bowl or a lidded pot.", "Top with the berries straight from frozen, the oats and the seeds. They thaw by the time you eat."],
    nameFor: { "soya-yoghurt": "Soya yoghurt bowl" },
    fridgeDays: 1,
  }),
  r("breakfast", "overnight-oats", {
    name: "Overnight oats with skyr", blurb: "Make three jars on Sunday and breakfast is done until Wednesday.",
    time: [4, 0], ahead: "Overnight in the fridge", kit: ["none"], washUp: 2, collections: ["no-cook", "gentle", "on-the-go"], cuisine: "British", cost: 1,
    ingredients: [L("oats", 40), L("skyr", 150), L("milk", 100), L("apple", 75)],
    steps: ["Stir the oats, skyr and milk together in a jar.", "Grate in the apple, skin and all. Lid on, into the fridge overnight.", "Eat cold, or loosen with a splash more milk."],
    only: { oats: ["gf-oats"] },
    fridgeDays: 3,
  }),
  r("breakfast", "microwave-eggs", {
    name: "Microwave scrambled eggs on toast", blurb: "Three eggs and a handful of spinach, cooked in the microwave.",
    time: [5, 0], kit: ["microwave"], washUp: 2, collections: ["microwave"], cuisine: "British", cost: 1,
    ingredients: [L("eggs", 174), L("spinach", 40), L("wholemeal-bread", 36)],
    steps: ["Beat the eggs in a microwave-safe mug or bowl with a pinch of salt and pepper. Stir in the spinach.", "Microwave for 45 seconds, stir, then 30 seconds at a time until just set.", "Pile onto the toast."],
    stepsFor: { "eggs>tofu": ["Crumble the tofu into a microwave-safe mug or bowl with a pinch of turmeric, salt and pepper. Stir in the spinach.", "Microwave for 1 minute, stir, then 30 seconds more until piping hot.", "Pile onto the toast."] },
    nameFor: { "eggs>tofu": "Microwave tofu scramble on toast" },
    fridgeDays: 0,
  }),
  r("breakfast", "cottage-salmon-crispbreads", {
    name: "Smoked salmon and cottage cheese crispbreads", blurb: "Salty, crunchy and cool, with no cooking at all.",
    time: [4, 0], kit: ["none"], washUp: 1, collections: ["no-cook"], cuisine: "Eastern European", cost: 3,
    ingredients: [L("cottage-cheese", 150), L("smoked-salmon", 50), L("rye-crispbread", 20), L("cucumber", 60), L("lemon", 10, true)],
    steps: ["Spread the cottage cheese over the crispbreads.", "Top with the smoked salmon and sliced cucumber, and a squeeze of lemon if you like."],
    fridgeDays: 0,
  }),
  r("breakfast", "beans-eggs-toast", {
    name: "Beans and eggs on toast", blurb: "A proper breakfast with the beans doing half the work.",
    time: [6, 1], kit: ["microwave"], washUp: 3, collections: ["microwave", "store-cupboard"], cuisine: "British", cost: 1,
    ingredients: [L("baked-beans", 200), L("eggs", 116), L("wholemeal-bread", 36)],
    steps: ["Microwave the beans in a covered bowl for 2 minutes, stirring halfway.", "Beat the eggs in a mug and microwave in 30-second bursts, stirring, until just set.", "Serve both on the toast."],
    stepsFor: { "eggs>tofu": { 2: "Crumble the tofu into a mug with a pinch of turmeric, salt and pepper, and microwave for 1 minute, stirring halfway." } },
    nameFor: { "eggs>tofu": "Beans and tofu scramble on toast" },
    fridgeDays: 0,
  }),
  r("breakfast", "breakfast-wrap", {
    name: "Bacon and egg breakfast wrap", blurb: "Eggs, bacon medallions and salsa, rolled up to go.",
    time: [9, 0], kit: ["hob"], washUp: 2, collections: ["on-the-go", "one-pan"], cuisine: "British", cost: 2,
    ingredients: [L("bacon-medallions", 50), L("eggs", 116), L("salsa", 30), L("wrap", 62)],
    steps: ["Fry the bacon in a non-stick pan with a little oil spray for 3 minutes, turning once. Push to one side.", "Scramble the eggs in the same pan.", "Spoon everything into the wrap with the salsa and roll it up."],
    stepsFor: { "eggs>tofu": { 2: "Crumble the tofu into the same pan with a pinch of turmeric and fry for 3 minutes." } },
    fridgeDays: 0,
  }),
  r("breakfast", "protein-porridge", {
    name: "Protein porridge", blurb: "Porridge made with milk, then stirred through with skyr.",
    time: [2, 4], kit: ["microwave"], washUp: 2, collections: ["microwave", "gentle"], cuisine: "British", cost: 1,
    ingredients: [L("oats", 40), L("milk", 250), L("skyr", 100), L("berries", 50, true)],
    steps: ["Mix the oats and milk in a big microwave-safe bowl. Cook for 2 minutes, stir, then 1 minute more.", "Let it stand for a minute, then stir in the skyr. Top with berries if you like."],
    only: { oats: ["gf-oats"] },
    fridgeDays: 0,
  }),
  r("breakfast", "pb-banana-toast", {
    name: "Peanut butter and banana toast with skyr", blurb: "Toast with peanut butter and banana, and a pot of skyr.",
    time: [2, 2], kit: ["none"], washUp: 2, collections: ["no-cook"], cuisine: "American", cost: 1,
    ingredients: [L("wholemeal-bread", 36), L("peanut-butter", 15), L("banana", 100), L("skyr", 150)],
    steps: ["Toast the bread and spread with the peanut butter.", "Slice the banana on top. Have the skyr on the side."],
    stepsFor: { seeds: { 1: "Toast the bread.", 2: "Slice the banana on top and scatter over the seeds. Have the skyr on the side." } },
    nameFor: { seeds: "Banana toast with seeds and skyr" },
    fridgeDays: 0,
  }),
  r("breakfast", "tofu-scramble", {
    name: "Tofu scramble on toast", blurb: "Crumbled tofu with peppers and turmeric. Plant-based and filling.",
    time: [10, 0], kit: ["hob"], washUp: 2, collections: ["one-pan"], cuisine: "British", cost: 1,
    ingredients: [L("tofu", 150), L("peppers", 80), L("spices", 2), L("oil", 5), L("wholemeal-bread", 36)],
    steps: ["Fry the peppers in the oil for 3 minutes.", "Crumble in the tofu with a good pinch of turmeric, salt and pepper, and cook for 4 minutes, stirring.", "Serve on the toast."],
    fridgeDays: 2,
  }),
  r("breakfast", "egg-muffins", {
    name: "Egg muffins, a batch of twelve", blurb: "Bake once, then breakfast is two muffins from the fridge.",
    serves: 6, time: [10, 22], kit: ["tray"], washUp: 3, collections: ["batch", "on-the-go", "family"], cuisine: "British", cost: 1,
    ingredients: [L("eggs", 116), L("spinach", 30), L("peppers", 30), L("feta", 20)],
    steps: ["Heat the oven to 180°C fan (or the air fryer to 170°C) and grease a 12-hole muffin tin or silicone cups.", "Beat the eggs with salt and pepper. Divide the chopped spinach, peppers and crumbled feta between the holes and pour the egg over.", "Bake for 18 to 20 minutes until set. Cool, then keep in the fridge."],
    only: { eggs: [] },
    fridgeDays: 3, freezes: true,
  }),
  r("breakfast", "shake-and-fruit", {
    name: "Protein milk and a banana", blurb: "For the mornings you're straight out of the door.",
    time: [1, 0], kit: ["none"], washUp: 0, collections: ["no-cook", "on-the-go", "gentle"], cuisine: "British", cost: 2,
    ingredients: [L("protein-milk", 330), L("banana", 100)],
    steps: ["Grab both on the way out."],
    fridgeDays: 0,
  }),
  r("breakfast", "sardines-toast", {
    name: "Sardines and tomatoes on toast", blurb: "A tin of sardines, warmed, on toast with cherry tomatoes.",
    time: [3, 2], kit: ["microwave"], washUp: 2, collections: ["store-cupboard", "microwave"], cuisine: "British", cost: 1,
    ingredients: [L("sardines-tin", 120), L("cherry-tomatoes", 80), L("wholemeal-bread", 36)],
    steps: ["Warm the sardines and halved tomatoes in a covered bowl in the microwave for 1 minute.", "Pile onto the toast and mash lightly with a fork."],
    nameFor: { "sardines-tin>baked-beans": "Beans and tomatoes on toast", "sardines-tin>mackerel-smoked": "Smoked mackerel and tomatoes on toast", "sardines-tin>tuna-tin": "Tuna and tomatoes on toast" },
    fridgeDays: 0, storeCupboard: "Use tinned chopped tomatoes instead of fresh.",
  }),
  r("breakfast", "salmon-bagel", {
    name: "Smoked salmon bagel", blurb: "A weekend bagel with cottage cheese and cucumber.",
    time: [3, 2], kit: ["none"], washUp: 1, collections: ["no-cook"], cuisine: "American", cost: 3,
    ingredients: [L("bagel", 85), L("smoked-salmon", 60), L("cottage-cheese", 60), L("cucumber", 40)],
    steps: ["Toast the bagel if you like.", "Spread with the cottage cheese and top with the salmon and cucumber. Lots of black pepper."],
    fridgeDays: 0,
  }),
  r("breakfast", "shakshuka", {
    name: "Quick shakshuka", blurb: "Eggs baked in spiced tomatoes and peppers, with feta and toast.",
    time: [5, 10], kit: ["hob"], washUp: 2, collections: ["one-pan"], cuisine: "Middle Eastern", cost: 1,
    ingredients: [L("eggs", 116), L("chopped-tomatoes", 200), L("peppers", 80), L("feta", 30), L("spices", 2), L("oil", 5), L("wholemeal-bread", 36)],
    steps: ["Soften the peppers (frozen sliced ones save chopping) in the oil in a small frying pan for 2 minutes. Add the tomatoes and a pinch of cumin and paprika, and simmer for 4 minutes.", "Make two dips, crack in the eggs, cover and cook for 5 to 6 minutes until the whites are set.", "Crumble over the feta. Eat with the toast."],
    only: { eggs: [] },
    fridgeDays: 0,
  }),

  /* ---------- lunch ---------- */
  r("lunch", "tuna-bean-salad", {
    name: "Tuna and white bean salad", blurb: "Tuna, beans, leaves and lemon, all in one bowl.",
    time: [6, 0], kit: ["none"], washUp: 1, collections: ["no-cook", "store-cupboard", "on-the-go"], cuisine: "Mediterranean", cost: 2,
    ingredients: [L("tuna-tin", 112), L("cannellini", 120), L("red-onion", 30), L("salad-leaves", 50), L("cherry-tomatoes", 60), L("lemon", 15)],
    steps: ["Drain the tuna and rinse the beans.", "Toss everything in a bowl with the lemon juice, a little olive oil, salt and pepper."],
    stepsFor: { "tuna-tin>chickpeas": { 1: "Rinse the chickpeas and beans." }, "tuna-tin>cooked-chicken": { 1: "Rinse the beans and tear the chicken into pieces." } },
    fridgeDays: 1, storeCupboard: "Skip the leaves and tomatoes and add tinned sweetcorn.",
  }),
  r("lunch", "chicken-hummus-wrap", {
    name: "Chicken and hummus wrap", blurb: "Ready-cooked chicken, hummus and crunchy salad.",
    time: [4, 0], kit: ["none"], washUp: 1, collections: ["no-cook", "on-the-go"], cuisine: "Middle Eastern", cost: 2,
    ingredients: [L("cooked-chicken", 90), L("hummus", 30), L("wrap", 62), L("salad-leaves", 40), L("cucumber", 40)],
    steps: ["Spread the hummus over the wrap.", "Add the chicken, leaves and sliced cucumber, then roll up tightly. Halve and wrap in foil if you're taking it out."],
    fridgeDays: 1,
  }),
  r("lunch", "lentil-feta-bowl", {
    name: "Lentil, feta and pepper bowl", blurb: "A pouch of lentils, jarred peppers and feta. Hot or cold.",
    time: [3, 1], kit: ["none"], washUp: 1, collections: ["no-cook", "on-the-go"], cuisine: "Mediterranean", cost: 2,
    ingredients: [L("lentil-pouch", 125), L("feta", 50), L("roasted-peppers", 80), L("spinach", 40), L("edamame", 50)],
    steps: ["Tip the lentils into a bowl. Warm in the microwave for a minute if you like, with the edamame.", "Stir through the spinach so it wilts, then top with the peppers and crumbled feta."],
    fridgeDays: 2,
  }),
  r("lunch", "egg-pitta", {
    name: "Egg mayo pitta with tomatoes", blurb: "Three boiled eggs, a little mayo and a warm pitta.",
    time: [5, 13], kit: ["hob"], washUp: 2, collections: ["on-the-go"], cuisine: "British", cost: 1,
    ingredients: [L("eggs", 174), L("light-mayo", 15), L("pitta", 58), L("cherry-tomatoes", 80), L("salad-leaves", 20)],
    steps: ["Boil the eggs for 9 minutes, then cool under cold water and peel.", "Mash with the mayo, salt and pepper.", "Fill the pitta with the egg and leaves. Tomatoes on the side."],
    only: { eggs: [] },
    nameFor: { "light-mayo>greek-yoghurt": "Egg and yoghurt pitta with tomatoes", "light-mayo>soya-yoghurt": "Egg and yoghurt pitta with tomatoes" },
    fridgeDays: 2,
  }),
  r("lunch", "prawn-rice-bowl", {
    name: "Sweet chilli prawn rice bowl", blurb: "Microwave rice, prawns, sweetcorn and edamame.",
    time: [4, 2], ahead: "Defrost the prawns in the fridge overnight", kit: ["microwave"], washUp: 1, collections: ["microwave", "on-the-go"], cuisine: "Thai", cost: 2,
    ingredients: [L("prawns", 120), L("rice-pouch", 125), L("sweetcorn", 60), L("edamame", 50), L("sweet-chilli", 15)],
    steps: ["Defrost the prawns in the fridge overnight, or under cold running water for 5 minutes.", "Microwave the rice and edamame together for 2 minutes.", "Top with the prawns and sweetcorn and drizzle with the sweet chilli sauce."],
    stepsFor: {
      tofu: ["Cut the tofu into small cubes.", "Microwave the rice, edamame and tofu together for 2 minutes.", "Top with the sweetcorn and drizzle with the sweet chilli sauce."],
      "cooked-chicken": ["Microwave the rice and edamame together for 2 minutes.", "Top with the chicken and sweetcorn and drizzle with the sweet chilli sauce."],
      edamame: ["Microwave the rice and edamame together for 2 minutes.", "Top with the sweetcorn and drizzle with the sweet chilli sauce."],
    },
    fridgeDays: 1,
  }),
  r("lunch", "red-lentil-soup", {
    name: "Spiced red lentil soup", blurb: "A big pot for the week, swirled with yoghurt.",
    serves: 4, time: [9, 22], kit: ["hob"], washUp: 2, collections: ["batch", "store-cupboard", "gentle"], cuisine: "South Asian", cost: 1,
    ingredients: [L("red-lentils", 60), L("carrots", 80), L("onion", 50), L("chopped-tomatoes", 100), L("stock", 250), L("curry-paste", 10), L("greek-yoghurt", 80)],
    steps: ["Soften the onion (frozen chopped onion saves time) and grated carrot in a big pan with a little oil for 5 minutes. Stir in the curry paste.", "Add the lentils, tomatoes and stock. Simmer for 20 minutes until the lentils fall apart.", "Blend if you like it smooth. Serve with a spoon of yoghurt on top."],
    fridgeDays: 3, freezes: true,
  }),
  r("lunch", "mackerel-beetroot", {
    name: "Smoked mackerel, beetroot and potato salad", blurb: "A filling plate with no cooking.",
    time: [5, 11], kit: ["none"], washUp: 1, collections: ["no-cook"], cuisine: "Eastern European", cost: 2,
    ingredients: [L("mackerel-smoked", 100), L("new-potatoes", 100), L("beetroot", 80), L("salad-leaves", 40), L("greek-yoghurt", 30)],
    steps: ["Halve the potatoes and microwave them in a covered bowl for 6 minutes, then spread out to cool for 5. Cooked ones from yesterday save the wait.", "Flake the mackerel over the leaves, potatoes and beetroot.", "Thin the yoghurt with a splash of water and lemon for a dressing."],
    stepsFor: { "mackerel-smoked>smoked-tofu": { 2: "Slice the smoked tofu over the leaves, potatoes and beetroot." } },
    fridgeDays: 1,
  }),
  r("lunch", "chickpea-smash", {
    name: "Chickpea smash sandwich with edamame", blurb: "Mashed chickpeas with soya yoghurt and cucumber. Plant-based.",
    time: [6, 1], kit: ["none"], washUp: 2, collections: ["no-cook", "store-cupboard"], cuisine: "British", cost: 1,
    ingredients: [L("chickpeas", 120), L("soya-yoghurt", 40), L("wholemeal-bread", 72), L("cucumber", 40), L("edamame", 60)],
    steps: ["Mash the chickpeas roughly with the yoghurt, salt, pepper and a squeeze of lemon if you have one.", "Sandwich with sliced cucumber. Have the edamame (defrosted or microwaved for a minute) on the side."],
    fridgeDays: 2,
  }),
  r("lunch", "halloumi-couscous", {
    name: "Halloumi and pepper couscous", blurb: "Kettle couscous with golden halloumi and spinach.",
    time: [6, 2], kit: ["kettle", "hob"], washUp: 2, collections: [], cuisine: "Mediterranean", cost: 2,
    ingredients: [L("couscous", 50), L("halloumi", 80), L("roasted-peppers", 80), L("spinach", 30), L("lemon", 10)],
    steps: ["Pour 75 ml of boiling water over the couscous, cover and leave for 5 minutes.", "Meanwhile fry the sliced halloumi in a dry pan for 2 minutes a side.", "Fluff the couscous, stir in the spinach, peppers and lemon juice, and top with the halloumi."],
    stepsFor: { "quinoa-pouch": { 1: "Microwave the quinoa for 1 minute, or as the pouch says." } },
    fridgeDays: 1,
  }),
  r("lunch", "turkey-bagel", {
    name: "Turkey, cheese and salad bagel", blurb: "A deli-style bagel with no cooking.",
    time: [3, 0], kit: ["none"], washUp: 1, collections: ["no-cook", "on-the-go"], cuisine: "American", cost: 2,
    ingredients: [L("bagel", 85), L("turkey-slices", 70), L("cheddar-light", 20), L("salad-leaves", 30), L("cherry-tomatoes", 60)],
    steps: ["Split the bagel and fill with the turkey, cheese and leaves.", "Tomatoes on the side."],
    fridgeDays: 1,
  }),
  r("lunch", "salmon-noodle-salad", {
    name: "Salmon, edamame and noodle salad", blurb: "Cold noodles, tinned salmon and a soy dressing.",
    time: [6, 0], kit: ["none"], washUp: 1, collections: ["no-cook", "on-the-go"], cuisine: "Japanese", cost: 2,
    ingredients: [L("salmon-tin", 100), L("noodles", 100), L("edamame", 60), L("cucumber", 60), L("soy-sauce", 10)],
    steps: ["Loosen the noodles under the cold tap. Defrost the edamame the same way.", "Toss with the cucumber, soy sauce and a few drops of lemon or vinegar. Flake the salmon on top."],
    stepsFor: {
      "salmon-tin>chickpeas": { 2: "Toss with the cucumber, soy sauce and a few drops of lemon or vinegar. Scatter the chickpeas on top." },
      "salmon-tin>cooked-chicken": { 2: "Toss with the cucumber, soy sauce and a few drops of lemon or vinegar. Scatter the chicken on top." },
    },
    fridgeDays: 1,
  }),
  r("lunch", "greek-chickpea-salad", {
    name: "Greek chickpea and lentil salad", blurb: "Chickpeas, lentils, feta and crunchy veg.",
    time: [8, 0], kit: ["none"], washUp: 1, collections: ["no-cook", "on-the-go"], cuisine: "Mediterranean", cost: 2,
    ingredients: [L("chickpeas", 120), L("lentil-pouch", 80), L("feta", 50), L("cucumber", 80), L("cherry-tomatoes", 80), L("red-onion", 20), L("olives", 20, true)],
    steps: ["Rinse the chickpeas. Chop the cucumber, tomatoes and onion.", "Toss with the lentils, a little olive oil, lemon or vinegar and dried oregano. Crumble over the feta."],
    fridgeDays: 2,
  }),
  r("lunch", "picnic-box", {
    name: "Picnic box", blurb: "Chicken, an egg, hummus, crunchy veg and oatcakes.",
    time: [5, 0], ahead: "An egg boiled ahead (boil a few at once for the week)", kit: ["hob"], washUp: 2, collections: ["on-the-go"], cuisine: "British", cost: 2,
    ingredients: [L("cooked-chicken", 60), L("eggs", 58), L("hummus", 40), L("carrots", 80), L("cucumber", 60), L("oatcakes", 20)],
    steps: ["Peel the egg you boiled ahead.", "Pack everything into a lidded box with the veg cut into sticks."],
    only: { eggs: [] },
    fridgeDays: 1,
  }),
  r("lunch", "tuna-jacket", {
    name: "Tuna and sweetcorn jacket potato", blurb: "A jacket potato done in the microwave, no oven needed.",
    time: [4, 10], kit: ["microwave"], washUp: 2, collections: ["microwave", "store-cupboard"], cuisine: "British", cost: 1,
    ingredients: [L("potato", 250), L("tuna-tin", 112), L("sweetcorn", 60), L("light-mayo", 15), L("salad-leaves", 40)],
    steps: ["Prick the potato and microwave for 8 to 10 minutes, turning halfway, until soft.", "Mix the tuna, sweetcorn and mayo, and pile on top. Leaves on the side."],
    stepsFor: { "potato>courgette": { 1: "Halve the courgette lengthways and microwave in a covered bowl for 4 minutes until soft." } },
    nameFor: { "potato>courgette": "Tuna and sweetcorn stuffed courgette" },
    fridgeDays: 1,
  }),
  r("lunch", "tofu-peanut-slaw", {
    name: "Smoked tofu and peanut slaw", blurb: "Crunchy carrot and pepper slaw with a peanut dressing. Plant-based.",
    time: [9, 0], kit: ["none"], washUp: 2, collections: ["no-cook", "on-the-go"], cuisine: "Thai", cost: 2,
    ingredients: [L("smoked-tofu", 120), L("carrots", 80), L("peppers", 60), L("edamame", 40), L("peanut-butter", 15), L("soy-sauce", 5)],
    steps: ["Grate the carrot and slice the pepper thinly.", "Whisk the peanut butter, soy sauce and a splash of hot water into a dressing.", "Toss with the veg, edamame and cubed smoked tofu."],
    stepsFor: { seeds: { 2: "Whisk the soy sauce with a squeeze of lemon and a splash of water into a dressing.", 3: "Toss with the veg, edamame and cubed smoked tofu, and scatter over the seeds." } },
    nameFor: { seeds: "Smoked tofu slaw with seeds" },
    fridgeDays: 2,
  }),

  /* ---------- dinner ---------- */
  r("dinner", "chicken-tikka-traybake", {
    name: "Chicken tikka traybake", blurb: "The takeaway favourite on one tray, with rice and spinach.",
    serves: 2, time: [10, 22], kit: ["tray", "microwave"], washUp: 2, collections: ["fakeaway", "family"], cuisine: "South Asian", cost: 2,
    ingredients: [L("chicken-breast", 150), L("curry-paste", 20), L("greek-yoghurt", 30), L("peppers", 100), L("onion", 50), L("spinach", 40), L("rice-pouch", 125)],
    steps: ["Heat the oven to 200°C fan or the air fryer to 190°C.", "Mix the chicken pieces with the curry paste and yoghurt. Spread on a tray with the sliced peppers and onion.", "Roast for 18 to 20 minutes, until the chicken is cooked through.", "Microwave the rice, stir in the spinach to wilt, and serve with the chicken."],
    fridgeDays: 2, freezes: true,
  }),
  r("dinner", "salmon-pesto-traybake", {
    name: "Salmon and green veg pesto traybake", blurb: "Salmon, green beans and tomatoes, with new potatoes.",
    serves: 2, time: [8, 24], kit: ["tray", "microwave"], washUp: 2, collections: ["one-pan"], cuisine: "Mediterranean", cost: 3,
    ingredients: [L("salmon-fillet", 120), L("green-beans", 100), L("cherry-tomatoes", 80), L("pesto", 15), L("new-potatoes", 150)],
    steps: ["Heat the oven to 200°C fan. Halve the potatoes and microwave them in a covered bowl for 4 minutes, then roast on a tray with a little oil for 10 minutes.", "Add the beans, tomatoes and salmon. Spread the pesto over the salmon.", "Roast for 10 to 12 minutes more, until the salmon flakes."],
    stepsFor: { tofu: { 3: "Roast for 10 to 12 minutes more, until the tofu is golden." }, "chicken-breast": { 3: "Roast for 10 to 12 minutes more, until the chicken is cooked through." } },
    fridgeDays: 1,
  }),
  r("dinner", "turkey-chilli", {
    name: "Turkey and bean chilli", blurb: "A big batch for the freezer and a jacket-potato lunch.",
    serves: 4, time: [12, 15], kit: ["hob", "microwave"], washUp: 2, collections: ["batch", "family", "one-pan"], cuisine: "Mexican", cost: 1, spicy: true,
    ingredients: [L("turkey-mince", 125), L("kidney-beans", 80), L("chopped-tomatoes", 200), L("onion", 50), L("peppers", 60), L("spices", 3), L("rice-pouch", 125)],
    steps: ["Brown the mince with the chopped onion and peppers in a big pan for 5 minutes.", "Stir in a heaped teaspoon each of chilli powder and cumin, then the tomatoes and beans.", "Simmer for 10 to 15 minutes. Serve with the microwaved rice."],
    fridgeDays: 3, freezes: true, storeCupboard: "Use frozen peppers and frozen chopped onion.",
  }),
  r("dinner", "prawn-fried-rice", {
    name: "Prawn and egg fried rice", blurb: "Quicker than the delivery and every bit as good.",
    time: [10, 0], ahead: "Defrost the prawns in the fridge overnight", kit: ["hob"], washUp: 1, collections: ["fakeaway", "one-pan"], cuisine: "Chinese", cost: 2,
    ingredients: [L("prawns", 100), L("eggs", 58), L("rice-pouch", 125), L("peas", 80), L("spring-onions", 15), L("soy-sauce", 10)],
    steps: ["Heat a little oil in a big frying pan or wok. Scramble the egg, then push it to the side.", "Add the rice (straight from the pouch), peas and prawns. Stir-fry for 4 minutes until piping hot.", "Stir through the soy sauce and sliced spring onions."],
    stepsFor: { "eggs>tofu": ["Heat a little oil in a big frying pan or wok. Crumble in the tofu with a pinch of turmeric and fry for 3 minutes, then push it to the side.", "Add the rice (straight from the pouch) and peas. Stir-fry for 4 minutes until piping hot.", "Stir through the soy sauce and sliced spring onions."] },
    fridgeDays: 1,
  }),
  r("dinner", "chicken-fajita-tray", {
    name: "Chicken fajita tray", blurb: "Everyone builds their own wrap. Good for families.",
    serves: 2, time: [9, 19], kit: ["tray"], washUp: 2, collections: ["fakeaway", "family", "one-pan"], cuisine: "Mexican", cost: 2,
    ingredients: [L("chicken-breast", 130), L("peppers", 120), L("onion", 50), L("spices", 3), L("wrap", 62), L("greek-yoghurt", 40)],
    steps: ["Heat the oven to 200°C fan or the air fryer to 190°C.", "Toss the sliced chicken, peppers and onion with the fajita spices (paprika, cumin, garlic) and a little oil.", "Roast for 15 to 18 minutes. Serve in warm wraps with yoghurt."],
    fridgeDays: 2,
  }),
  r("dinner", "sausage-gnocchi-tray", {
    name: "Sausage and gnocchi traybake", blurb: "Crispy gnocchi, chicken sausages and sweet roast peppers.",
    serves: 2, time: [6, 29], kit: ["tray"], washUp: 1, collections: ["one-pan", "family"], cuisine: "Italian", cost: 2,
    ingredients: [L("chicken-sausages", 134), L("gnocchi", 150), L("peppers", 100), L("cherry-tomatoes", 80)],
    steps: ["Heat the oven to 200°C fan. Toss the gnocchi, peppers and tomatoes with a little oil and dried herbs on a tray.", "Snip the sausages into chunks and add.", "Roast for 20 to 25 minutes, shaking halfway, until golden."],
    stepsFor: { "chicken-sausages>quorn-pieces": { 2: "Add the Quorn pieces." }, "chicken-sausages>smoked-tofu": { 2: "Cut the smoked tofu into chunks and add." } },
    fridgeDays: 2,
  }),
  r("dinner", "cod-tomato-olive", {
    name: "Cod in tomato and olive sauce with couscous", blurb: "Frozen fish fillets in a quick Mediterranean sauce.",
    time: [7, 9], ahead: "Defrost the cod in the fridge overnight, or allow 4 more minutes from frozen", kit: ["hob", "kettle"], washUp: 2, collections: ["gentle"], cuisine: "Mediterranean", cost: 2,
    ingredients: [L("cod-fillet", 130), L("chopped-tomatoes", 200), L("olives", 20), L("spinach", 40), L("couscous", 50)],
    steps: ["Simmer the tomatoes with a little garlic and the olives in a frying pan for 3 minutes.", "Sit the defrosted cod in the sauce, cover and cook for 8 to 10 minutes (12 to 14 from frozen), until it flakes.", "Meanwhile pour 75 ml boiling water over the couscous and cover. Stir the spinach into the sauce at the end."],
    stepsFor: {
      tofu: { 2: "Add the cubed tofu, cover and cook for 6 minutes until hot through." },
      prawns: { 2: "Add the prawns, cover and cook for 4 minutes until piping hot." },
      "chicken-breast": { 2: "Add the sliced chicken, cover and cook for 8 to 10 minutes until cooked through." },
      "quinoa-pouch": { 3: "Meanwhile microwave the quinoa for 1 minute. Stir the spinach into the sauce at the end." },
    },
    nameFor: { prawns: "Prawns in tomato and olive sauce with couscous" },
    fridgeDays: 1,
  }),
  r("dinner", "paneer-pea-curry", {
    name: "Paneer and pea curry", blurb: "A mild curry from a jar of paste and the freezer.",
    serves: 2, time: [8, 8], kit: ["hob", "microwave"], washUp: 2, collections: ["one-pan", "family"], cuisine: "South Asian", cost: 2,
    ingredients: [L("paneer", 100), L("peas", 100), L("chopped-tomatoes", 150), L("onion", 50), L("curry-paste", 20), L("rice-pouch", 125)],
    steps: ["Fry the chopped onion with a little oil for 4 minutes, then stir in the curry paste for a minute.", "Add the tomatoes and cubed paneer and simmer for 8 minutes. Add the peas for the last 3.", "Serve with the microwaved rice."],
    fridgeDays: 2, freezes: true,
  }),
  r("dinner", "pork-stir-fry", {
    name: "Pork and veg stir-fry with noodles", blurb: "Pork, veg and noodles in one wok.",
    time: [12, 0], kit: ["hob"], washUp: 1, collections: ["fakeaway", "one-pan"], cuisine: "Chinese", cost: 2,
    ingredients: [L("pork-loin", 130), L("stir-fry-veg", 150), L("noodles", 150), L("soy-sauce", 10), L("ginger", 5)],
    steps: ["Slice the pork thinly. Stir-fry in a little hot oil for 4 minutes.", "Add the veg and ginger and cook for 3 minutes.", "Add the noodles and soy sauce and toss until hot."],
    fridgeDays: 1,
  }),
  r("dinner", "chicken-chorizo-rice", {
    name: "Chicken and chorizo one-pot rice", blurb: "Smoky, paella-style rice without the wait.",
    serves: 2, time: [13, 5], kit: ["hob"], washUp: 1, collections: ["one-pan", "family"], cuisine: "Mediterranean", cost: 2,
    ingredients: [L("chicken-breast", 120), L("chorizo", 25), L("peppers", 80), L("chopped-tomatoes", 100), L("peas", 50), L("rice-pouch", 125)],
    steps: ["Fry the diced chorizo for 2 minutes until it releases its oil. Add the chicken pieces and peppers and cook for 6 minutes.", "Add the tomatoes and a pinch of paprika and simmer for 3 minutes.", "Stir in the rice and peas and cook until piping hot."],
    stepsFor: { "chorizo>smoked-tofu": { 1: "Fry the diced smoked tofu in a little oil for 2 minutes. Add the chicken pieces and peppers and cook for 6 minutes." } },
    nameFor: { "chorizo>smoked-tofu": "Smoky chicken one-pot rice" },
    fridgeDays: 2,
  }),
  r("dinner", "wrap-pizza", {
    name: "Chicken wrap pizza", blurb: "A crisp wrap base, passata and mozzarella.",
    time: [4, 13], kit: ["tray"], washUp: 1, collections: ["fakeaway", "family"], cuisine: "Italian", cost: 2,
    ingredients: [L("wrap", 62), L("passata", 50), L("mozzarella-light", 60), L("cooked-chicken", 60), L("peppers", 50), L("salad-leaves", 50)],
    steps: ["Heat the oven to 200°C fan or the air fryer to 180°C.", "Spread the passata over the wrap and top with the chicken, peppers and torn mozzarella.", "Bake for 6 to 8 minutes until crisp. Salad on the side."],
    stepsFor: {
      "mozzarella-light>smoked-tofu": { 2: "Spread the passata over the wrap and top with the chicken, peppers and thin slices of smoked tofu." },
      "mozzarella-light>smoked-tofu+cooked-chicken>smoked-tofu": { 2: "Spread the passata over the wrap and top with thin slices of smoked tofu and the peppers." },
    },
    fridgeDays: 0,
  }),
  r("dinner", "lentil-bolognese", {
    name: "Beef and lentil bolognese", blurb: "Half mince, half lentils. A freezer staple.",
    serves: 4, time: [10, 20], kit: ["hob"], washUp: 3, collections: ["batch", "family"], cuisine: "Italian", cost: 1,
    ingredients: [L("beef-mince", 75), L("red-lentils", 25), L("passata", 150), L("onion", 50), L("carrots", 50), L("mushrooms", 60, true), L("stock", 80), L("pasta", 70)],
    steps: ["Brown the mince with the onion (frozen chopped onion saves time), grated carrot and the mushrooms, if you're using them, for 6 minutes.", "Add the lentils, passata and stock. Simmer for 20 minutes, adding a splash of water if it thickens too much.", "Cook the pasta while it simmers."],
    fridgeDays: 3, freezes: true,
  }),
  r("dinner", "thai-green-curry", {
    name: "Thai green chicken curry", blurb: "Coconut, green beans and peppers, with rice.",
    serves: 2, time: [8, 9], kit: ["hob", "microwave"], washUp: 2, collections: ["fakeaway", "one-pan"], cuisine: "Thai", cost: 2, spicy: true,
    ingredients: [L("chicken-breast", 130), L("thai-paste", 20), L("coconut-milk", 100), L("green-beans", 80), L("peppers", 50), L("rice-pouch", 125)],
    steps: ["Fry the paste in a little oil for a minute, then add the sliced chicken and cook for 4 minutes.", "Pour in the coconut milk and add the beans and peppers. Simmer for 8 minutes.", "Serve with the microwaved rice."],
    fridgeDays: 2, freezes: true,
  }),
  r("dinner", "chana-masala", {
    name: "Chickpea and spinach curry", blurb: "Chana masala from the store cupboard. Plant-based.",
    serves: 4, time: [8, 17], kit: ["hob", "microwave"], washUp: 2, collections: ["batch", "store-cupboard"], cuisine: "South Asian", cost: 1,
    ingredients: [L("chickpeas", 200), L("red-lentils", 25), L("chopped-tomatoes", 150), L("onion", 50), L("spinach", 60), L("curry-paste", 20), L("rice-pouch", 125)],
    steps: ["Soften the onion in a little oil for 5 minutes, then stir in the curry paste.", "Add the chickpeas, lentils, tomatoes and a mugful of water. Simmer for 15 minutes until the lentils are soft.", "Stir through the spinach. Serve with rice."],
    fridgeDays: 3, freezes: true, storeCupboard: "Use frozen spinach and frozen chopped onion.",
  }),
  r("dinner", "air-fryer-fish-chips", {
    name: "Air-fryer fish, chips and peas", blurb: "The chippy classic, crisp and quick.",
    time: [7, 23], kit: ["tray", "microwave"], washUp: 2, collections: ["fakeaway", "family"], cuisine: "British", cost: 2,
    ingredients: [L("cod-fillet", 150), L("potato", 200), L("peas", 100), L("lemon", 15)],
    steps: ["Cut the potato into chips, toss with a teaspoon of oil and salt, and air-fry at 200°C for 18 to 20 minutes (or oven-bake at 220°C fan for 25), shaking halfway.", "Add the fish, seasoned with salt, pepper and lemon zest, for the last 10 to 12 minutes.", "Microwave the peas and serve with lemon."],
    stepsFor: { prawns: { 2: "Add the prawns, seasoned with salt, pepper and lemon zest, for the last 4 to 5 minutes, until piping hot." } },
    nameFor: { prawns: "Air-fryer prawns, chips and peas", tofu: "Air-fryer tofu, chips and peas" },
    fridgeDays: 0,
  }),
  r("dinner", "smash-burger", {
    name: "Smash burger with salad", blurb: "Thin, crisp-edged beef burgers in a wholemeal roll.",
    serves: 2, time: [13, 0], kit: ["hob"], washUp: 2, collections: ["fakeaway", "family"], cuisine: "American", cost: 2,
    ingredients: [L("beef-mince", 125), L("roll", 60), L("cheddar-light", 15), L("salad-leaves", 40), L("cherry-tomatoes", 60)],
    steps: ["Roll the mince into balls. Heat a dry heavy frying pan until very hot.", "Add a ball, press flat with a spatula and cook for 2 minutes a side until cooked through. Top with the cheese for the last minute.", "Serve in the toasted roll with leaves and sliced tomato."],
    only: { "beef-mince": ["turkey-mince"] },
    stepsFor: { "roll>gf-bread": { 3: "Serve on toasted gluten-free bread with leaves and sliced tomato." } },
    nameFor: { "roll>gf-bread": "Smash burger on toast with salad" },
    fridgeDays: 0,
  }),
  r("dinner", "chicken-shawarma", {
    name: "Chicken shawarma pittas", blurb: "Spiced chicken thighs with cool yoghurt and cucumber.",
    serves: 2, time: [9, 21], kit: ["tray"], washUp: 2, collections: ["fakeaway", "family"], cuisine: "Middle Eastern", cost: 2,
    ingredients: [L("chicken-thigh", 150), L("spices", 3), L("pitta", 58), L("greek-yoghurt", 40), L("cucumber", 50), L("red-onion", 20), L("salad-leaves", 30)],
    steps: ["Heat the oven to 200°C fan or the air fryer to 190°C. Toss the chicken with cumin, paprika, cinnamon, garlic and a little oil.", "Roast for 20 minutes until cooked through, then slice.", "Fill warm pittas with the chicken, salad, cucumber and onion, and spoon over the yoghurt."],
    fridgeDays: 2, freezes: true,
  }),
  r("dinner", "salmon-poke", {
    name: "Salmon poke bowl", blurb: "Rice, salmon, edamame and cucumber with soy. Barely any cooking.",
    time: [5, 2], kit: ["microwave"], washUp: 1, collections: ["fakeaway", "microwave"], cuisine: "Japanese", cost: 2,
    ingredients: [L("salmon-tin", 110), L("rice-pouch", 125), L("edamame", 60), L("cucumber", 60), L("soy-sauce", 10)],
    steps: ["Microwave the rice and edamame together for 2 minutes.", "Top with the salmon and cubed cucumber, and drizzle with soy sauce. Add sesame seeds or chilli if you like."],
    fridgeDays: 1,
  }),
  r("dinner", "tofu-peanut-stir-fry", {
    name: "Peanut tofu stir-fry", blurb: "Crisp tofu, veg and rice noodles in a peanut sauce. Plant-based.",
    time: [13, 0], kit: ["hob"], washUp: 2, collections: ["one-pan"], cuisine: "Thai", cost: 2,
    ingredients: [L("tofu", 200), L("stir-fry-veg", 150), L("rice-noodles", 150), L("peanut-butter", 15), L("soy-sauce", 10)],
    steps: ["Pat the tofu dry, cube it and fry in a little oil for 6 minutes until golden.", "Add the veg and stir-fry for 3 minutes.", "Whisk the peanut butter, soy sauce and 3 tablespoons of hot water. Add with the noodles and toss until hot."],
    stepsFor: { seeds: { 3: "Mix the soy sauce with 3 tablespoons of hot water. Add with the noodles and toss until hot, then scatter over the seeds." } },
    nameFor: { seeds: "Crispy tofu stir-fry with seeds" },
    fridgeDays: 2,
  }),
  r("dinner", "turkey-meatballs", {
    name: "Turkey meatballs in tomato sauce", blurb: "Baked meatballs, a quick sauce and pasta. Freezes well.",
    serves: 4, time: [12, 13], kit: ["tray", "hob"], washUp: 3, collections: ["batch", "family"], cuisine: "Italian", cost: 1,
    ingredients: [L("turkey-mince", 125), L("spices", 2), L("passata", 150), L("spinach", 50), L("pasta", 70)],
    steps: ["Heat the oven to 200°C fan. Mix the mince with dried herbs, salt and pepper and roll into about 16 golf-ball-sized balls. Bake for 15 minutes.", "Simmer the passata with a little garlic for 10 minutes and cook the pasta.", "Stir the meatballs and spinach into the sauce and serve with the pasta."],
    only: { "turkey-mince": ["beef-mince"] },
    fridgeDays: 3, freezes: true,
  }),
  r("dinner", "sweet-potato-curry", {
    name: "Chickpea and sweet potato curry", blurb: "Creamy, mild and plant-based, with a big batch for later.",
    serves: 4, time: [10, 22], kit: ["hob"], washUp: 2, collections: ["batch", "family"], cuisine: "South Asian", cost: 1,
    ingredients: [L("chickpeas", 180), L("red-lentils", 35), L("sweet-potato", 120), L("spinach", 80), L("coconut-milk", 80), L("curry-paste", 15), L("soya-yoghurt", 50)],
    steps: ["Fry the curry paste in a little oil for a minute. Add the cubed sweet potato, lentils, chickpeas, coconut milk and a mugful of water.", "Simmer for 20 minutes until the sweet potato is soft.", "Stir in the spinach and serve with a spoon of yoghurt."],
    fridgeDays: 3, freezes: true,
  }),
  r("dinner", "chicken-chickpea-stew", {
    name: "Moroccan chicken and chickpea stew", blurb: "Warm spices, tomatoes and chickpeas, with couscous.",
    serves: 4, time: [12, 22], kit: ["hob", "kettle"], washUp: 2, collections: ["batch", "family", "one-pan"], cuisine: "Middle Eastern", cost: 2,
    ingredients: [L("chicken-thigh", 130), L("chickpeas", 100), L("chopped-tomatoes", 200), L("onion", 50), L("spices", 3), L("couscous", 40)],
    steps: ["Brown the chicken pieces with the chopped onion for 6 minutes. Stir in cumin, cinnamon and paprika.", "Add the tomatoes and chickpeas and simmer for 20 minutes.", "Pour 60 ml boiling water over the couscous, cover for 5 minutes and serve with the stew."],
    stepsFor: { "quinoa-pouch": { 3: "Microwave the quinoa for 1 minute and serve with the stew." } },
    fridgeDays: 3, freezes: true,
  }),
  r("dinner", "jerk-chicken-rice-peas", {
    name: "Jerk-spiced chicken with rice and peas", blurb: "Jerk-spiced chicken thighs with coconut rice and kidney beans.",
    serves: 2, time: [8, 22], kit: ["tray", "microwave"], washUp: 2, collections: ["family"], cuisine: "Caribbean", cost: 2, spicy: true,
    ingredients: [L("chicken-thigh", 150), L("spices", 4), L("peppers", 80), L("rice-pouch", 125), L("kidney-beans", 60), L("coconut-milk", 50)],
    steps: ["Heat the oven to 200°C fan or the air fryer to 190°C. Rub the chicken with jerk seasoning and a little oil and roast with the peppers for 20 minutes.", "Microwave the rice with the beans and coconut milk for 2 to 3 minutes, stirring halfway.", "Serve together."],
    fridgeDays: 2, freezes: true,
  }),
  r("dinner", "peanut-stew", {
    name: "West African-style peanut stew", blurb: "Chicken, sweet potato and spinach in a rich tomato and peanut sauce.",
    serves: 4, time: [11, 22], kit: ["hob"], washUp: 2, collections: ["batch", "family", "one-pan"], cuisine: "West African", cost: 1,
    ingredients: [L("chicken-thigh", 130), L("peanut-butter", 20), L("chopped-tomatoes", 150), L("sweet-potato", 100), L("spinach", 60), L("onion", 40), L("stock", 150)],
    steps: ["Brown the chicken and onion (frozen chopped onion saves time) for 6 minutes.", "Stir in the peanut butter, tomatoes, stock and cubed sweet potato. Simmer for 20 minutes.", "Stir through the spinach until wilted."],
    stepsFor: { seeds: { 2: "Stir in the tomatoes, stock and cubed sweet potato. Simmer for 20 minutes.", 3: "Stir through the spinach until wilted, and scatter over the seeds." } },
    nameFor: { seeds: "West African-style chicken and sweet potato stew" },
    fridgeDays: 3, freezes: true,
  }),
  r("dinner", "chicken-goulash", {
    name: "Paprika chicken with new potatoes", blurb: "A quick goulash with peppers and a swirl of yoghurt.",
    serves: 4, time: [10, 17], kit: ["hob"], washUp: 2, collections: ["batch", "one-pan", "family", "gentle"], cuisine: "Eastern European", cost: 2,
    ingredients: [L("chicken-breast", 140), L("peppers", 100), L("chopped-tomatoes", 150), L("onion", 50), L("spices", 3), L("new-potatoes", 150), L("greek-yoghurt", 30)],
    steps: ["Fry the chicken with frozen sliced peppers and chopped onion for 6 minutes. Stir in a heaped teaspoon of sweet paprika.", "Add the tomatoes and halved new potatoes with a splash of water. Cover and simmer for 15 minutes until the potatoes are tender.", "Serve with a spoon of yoghurt."],
    fridgeDays: 2, freezes: true,
  }),
  r("dinner", "halloumi-veg-tray", {
    name: "Halloumi and roast veg traybake", blurb: "Golden halloumi with courgette, peppers and couscous.",
    serves: 2, time: [9, 23], kit: ["tray", "kettle"], washUp: 2, collections: ["one-pan"], cuisine: "Mediterranean", cost: 2,
    ingredients: [L("halloumi", 100), L("courgette", 100), L("peppers", 100), L("red-onion", 40), L("cherry-tomatoes", 60), L("couscous", 40)],
    steps: ["Heat the oven to 200°C fan. Roast the chopped veg with a little oil for 12 minutes.", "Add the sliced halloumi and roast for 8 to 10 minutes more.", "Pour 60 ml boiling water over the couscous, cover for 5 minutes and serve underneath."],
    stepsFor: { "quinoa-pouch": { 3: "Microwave the quinoa for 1 minute and serve it underneath." } },
    fridgeDays: 1,
  }),
  r("dinner", "black-bean-chilli", {
    name: "Black bean chilli", blurb: "Beans and soya mince with smoky spices. Plant-based.",
    serves: 4, time: [9, 14], kit: ["hob", "microwave"], washUp: 2, collections: ["batch", "store-cupboard", "family", "one-pan"], cuisine: "Mexican", cost: 1, spicy: true,
    ingredients: [L("soya-mince", 100), L("black-beans", 120), L("kidney-beans", 80), L("chopped-tomatoes", 200), L("peppers", 80), L("spices", 3), L("rice-pouch", 125)],
    steps: ["Fry the peppers for 3 minutes, then add the soya mince and cook for 4 minutes.", "Stir in chilli powder, cumin and smoked paprika, then the tomatoes and beans. Simmer for 12 minutes.", "Serve with the microwaved rice."],
    fridgeDays: 3, freezes: true,
  }),
  r("dinner", "ginger-chicken-broth", {
    name: "Ginger chicken, rice and greens", blurb: "A gentle bowl for the days your stomach wants something plain.",
    time: [6, 11], kit: ["hob"], washUp: 1, collections: ["gentle", "one-pan"], cuisine: "Chinese", cost: 2,
    ingredients: [L("chicken-breast", 130), L("broccoli", 100), L("rice-pouch", 125), L("stock", 300), L("ginger", 5), L("soy-sauce", 5)],
    steps: ["Bring the stock and ginger to a simmer in a saucepan. Add the thinly sliced chicken and poach for 8 minutes.", "Add the broccoli for the last 4 minutes and the rice for the last 2.", "Season with a few drops of soy sauce."],
    nameFor: { "ginger>spices": "Spiced chicken, rice and greens" },
    fridgeDays: 2,
  }),
  r("dinner", "salmon-pea-pasta", {
    name: "Lemony salmon and pea pasta", blurb: "Flaked salmon, peas and spinach through fresh pasta, all in one pan.",
    time: [6, 11], kit: ["hob"], washUp: 2, collections: [], cuisine: "Italian", cost: 2,
    ingredients: [L("salmon-fillet", 100), L("fresh-pasta", 125), L("peas", 80), L("spinach", 50), L("greek-yoghurt", 40), L("lemon", 15)],
    steps: ["Boil a kettle and pour it into a saucepan. Poach the salmon in the simmering water for 8 minutes, adding the fresh pasta and peas for the last 3.", "Drain, keeping a splash of water. Lift out the salmon and flake it.", "Stir the spinach, yoghurt, lemon and salmon through the pasta with a little cooking water."],
    stepsFor: {
      tofu: ["Boil a kettle and pour it into a saucepan. Meanwhile fry the cubed tofu in a little oil in a frying pan for 5 minutes until golden.", "Cook the fresh pasta and peas in the simmering water for 3 minutes, then drain, keeping a splash of water.", "Stir the spinach, yoghurt, lemon and tofu through the pasta with a little cooking water."],
      "gf-pasta": ["Boil a kettle and pour it into a saucepan. Cook the pasta for 2 minutes, then add the salmon and poach for 8 minutes more, adding the peas for the last 3. Dried pasta can take longer, so check the pack.", "Drain, keeping a splash of water. Lift out the salmon and flake it.", "Stir the spinach, yoghurt, lemon and salmon through the pasta with a little cooking water."],
      "tofu+gf-pasta": ["Boil a kettle and pour it into a saucepan. Cook the pasta for 10 minutes, or the time on the pack, adding the peas for the last 3.", "Meanwhile fry the cubed tofu in a little oil in a frying pan for 5 minutes until golden.", "Drain the pasta, keeping a splash of water. Stir the spinach, yoghurt, lemon and tofu through with a little cooking water."],
      "chicken-breast": { 2: "Drain, keeping a splash of water. Lift out the chicken and shred it with two forks." },
    },
    fridgeDays: 1,
  }),
  r("dinner", "red-lentil-dhal", {
    name: "Red lentil dhal", blurb: "Soft, mild and soothing. Freezes in portions.",
    serves: 4, time: [7, 22], kit: ["hob", "microwave"], washUp: 2, collections: ["batch", "store-cupboard", "gentle"], cuisine: "South Asian", cost: 1,
    ingredients: [L("red-lentils", 80), L("chopped-tomatoes", 100), L("spinach", 60), L("onion", 40), L("ginger", 5), L("spices", 2), L("soya-yoghurt", 60), L("rice-pouch", 100)],
    steps: ["Soften the onion (frozen chopped onion saves time) with the ginger, a little garlic, turmeric and cumin in a pan for 4 minutes.", "Add the lentils, tomatoes and 3 mugs of water. Simmer for 20 minutes, stirring now and then, until thick and soft.", "Stir through the spinach. Serve with rice and a spoon of yoghurt."],
    fridgeDays: 3, freezes: true, storeCupboard: "Use frozen spinach and frozen chopped onion.",
  }),

  /* ---------- snacks ---------- */
  r("snack", "egg-pot", {
    name: "Egg pot with spinach", blurb: "Two boiled eggs on a bed of spinach. Boil a batch for the week.",
    time: [3, 13], kit: ["hob"], washUp: 1, collections: ["on-the-go", "gentle"], cuisine: "British", cost: 1,
    ingredients: [L("eggs", 116), L("spinach", 30)],
    steps: ["Boil the eggs for 9 minutes, cool in cold water and peel.", "Pack on top of the spinach in a little pot."],
    only: { eggs: [] },
    fridgeDays: 2,
  }),
  r("snack", "skyr-berries", {
    name: "Skyr and berries", blurb: "Thick, cool and ready to eat.",
    time: [1, 0], kit: ["none"], washUp: 1, collections: ["no-cook", "gentle"], cuisine: "British", cost: 1,
    ingredients: [L("skyr", 150), L("berries", 50)],
    steps: ["Spoon the skyr into a bowl and top with the berries."],
    fridgeDays: 1,
  }),
  r("snack", "cottage-oatcakes", {
    name: "Cottage cheese, tomatoes and oatcakes", blurb: "A savoury plate for the afternoon dip.",
    time: [2, 0], kit: ["none"], washUp: 1, collections: ["no-cook"], cuisine: "British", cost: 1,
    ingredients: [L("cottage-cheese", 120), L("cherry-tomatoes", 60), L("oatcakes", 20)],
    steps: ["Spoon the cottage cheese onto the oatcakes, with the tomatoes on the side. Lots of black pepper."],
    fridgeDays: 0,
  }),
  r("snack", "chicken-pieces", {
    name: "Cooked chicken pieces", blurb: "A small pack from the chiller, straight from the fridge.",
    time: [0, 0], kit: ["none"], washUp: 0, collections: ["no-cook", "on-the-go"], cuisine: "British", cost: 2,
    ingredients: [L("cooked-chicken", 75)],
    steps: ["Open and eat. Add a few cherry tomatoes if you have them."],
    nameFor: { "tuna-tin": "Tinned tuna", "smoked-tofu": "Smoked tofu pieces", "quorn-pieces": "Quorn pieces" },
    fridgeDays: 2,
  }),
  r("snack", "chilli-edamame", {
    name: "Chilli edamame", blurb: "Warm edamame with a pinch of chilli salt.",
    time: [1, 2], kit: ["microwave"], washUp: 1, collections: ["microwave"], cuisine: "Japanese", cost: 1, spicy: true,
    ingredients: [L("edamame", 100), L("chilli-flakes", 1)],
    steps: ["Microwave the edamame in a covered bowl for 2 minutes.", "Sprinkle with chilli flakes and a pinch of salt."],
    fridgeDays: 1,
  }),
  r("snack", "protein-milk", {
    name: "Protein milk drink", blurb: "A chilled bottle when you're out and about.",
    time: [0, 0], kit: ["none"], washUp: 0, collections: ["no-cook", "on-the-go", "gentle"], cuisine: "British", cost: 2,
    ingredients: [L("protein-milk", 330)],
    steps: ["Shake and drink."],
    fridgeDays: 0,
  }),
  r("snack", "hummus-edamame", {
    name: "Hummus, carrots and edamame", blurb: "Crunchy veg with dip and a handful of beans.",
    time: [4, 0], kit: ["none"], washUp: 1, collections: ["no-cook", "on-the-go"], cuisine: "Middle Eastern", cost: 1,
    ingredients: [L("hummus", 50), L("carrots", 60), L("edamame", 60)],
    steps: ["Cut the carrots into sticks. Defrost the edamame under the cold tap.", "Pack with the hummus."],
    fridgeDays: 1,
  }),
  r("snack", "tuna-sweetcorn-pot", {
    name: "Tuna and sweetcorn pot", blurb: "Half a tin of tuna with sweetcorn and a little mayo.",
    time: [2, 0], kit: ["none"], washUp: 1, collections: ["no-cook", "store-cupboard"], cuisine: "British", cost: 1,
    ingredients: [L("tuna-tin", 80), L("sweetcorn", 40), L("light-mayo", 10)],
    steps: ["Mix everything in a small pot. Keep the rest of the tin covered in the fridge for tomorrow."],
    fridgeDays: 1,
  }),
  r("snack", "apple-pb-yoghurt", {
    name: "Apple with peanut butter yoghurt dip", blurb: "Sliced apple and a quick sweet-salty dip.",
    time: [2, 0], kit: ["none"], washUp: 1, collections: ["no-cook"], cuisine: "American", cost: 1,
    ingredients: [L("apple", 150), L("peanut-butter", 15), L("greek-yoghurt", 100)],
    steps: ["Stir the peanut butter into the yoghurt.", "Dip in the sliced apple."],
    nameFor: { seeds: "Apple with a seedy yoghurt dip" },
    fridgeDays: 0,
  }),
  r("snack", "cheese-oatcakes", {
    name: "Cheese, oatcakes and an apple", blurb: "A classic, in sensible pieces.",
    time: [2, 0], kit: ["none"], washUp: 0, collections: ["no-cook", "on-the-go"], cuisine: "British", cost: 1,
    ingredients: [L("cheddar-light", 30), L("oatcakes", 20), L("apple", 100)],
    steps: ["Slice the cheese and pack with the oatcakes and apple."],
    fridgeDays: 0,
  }),
  r("snack", "soya-yoghurt-pot", {
    name: "Soya yoghurt, berries and seeds", blurb: "A plant-based pot with a crunchy top.",
    time: [1, 0], kit: ["none"], washUp: 1, collections: ["no-cook", "gentle"], cuisine: "British", cost: 1,
    ingredients: [L("soya-yoghurt", 150), L("berries", 50), L("seeds", 10)],
    steps: ["Top the yoghurt with the berries and seeds."],
    fridgeDays: 0,
  }),
];

export const RECIPE = Object.fromEntries(RECIPES.map((r) => [r.id, r])) as Record<string, Recipe>;

/**
 * Meal-deal formulas for busy days (plan §5.3), held as formulas, not products, because shelves change.
 * Shown as cards, not planned as recipes. Protein figures are typical ranges and must be checked against labels.
 */
export const MEAL_DEALS = [
  { id: "deal-chicken", name: "Chicken sandwich, egg pot and water", detail: "A chicken or chicken club sandwich, an egg protein pot instead of crisps, and water or a zero drink." },
  { id: "deal-wrap", name: "High-protein wrap and chicken bites", detail: "Look for a wrap labelled high protein, with a pot of cooked chicken and sparkling water." },
  { id: "deal-veggie", name: "Falafel wrap, edamame and protein milk", detail: "The vegetarian option: a falafel or halloumi wrap, an edamame pot and a protein milk as the drink." },
  { id: "deal-fish", name: "Tuna sandwich and a skyr pot", detail: "A tuna sweetcorn sandwich with a skyr or high-protein yoghurt and water." },
];

/** Ordering-well notes for the planned takeaway night (plan §5.1). Never "good" or "bad", just what helps. */
export const ORDERING_WELL: Record<string, string> = {
  Chinese: "Pick a protein-led main like chicken and cashew or prawn stir-fry, and share a rice.",
  Indian: "Tandoori or tikka dishes and a dal go a long way. Add a raita.",
  Pizza: "A thin base with chicken or prawns, and a side salad to share.",
  "Fish and chips": "A regular portion of fish, a small chips and mushy peas.",
  Kebab: "A chicken shish in pitta with lots of salad and the sauce on the side.",
  Thai: "A curry or stir-fry with chicken, prawns or tofu, and plain rice.",
};
