// Copies the meal planner bundle (window.LandingFood) from packages/engine into src/food.js, so the prototype keeps
// working with no build step. Run `pnpm --filter @landing/engine build` first after changing the engine or the
// recipes; the prototype build runs this.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = dirname(fileURLToPath(import.meta.url));
const bundle = readFileSync(resolve(dir, '../../../packages/engine/dist/landing-food.js'), 'utf8');
const out = `/* Generated by scripts/food.mjs from packages/engine/dist/landing-food.js. Do not edit. */\n${bundle}`;
writeFileSync(resolve(dir, '../src/food.js'), out);
console.log(`src/food.js: ${Math.round(out.length / 1024)} KB`);
