// Copies the exercise-loop bundle (window.LandingMotion) from packages/motion into src/motion.js, so the prototype
// keeps working with no build step. Run `pnpm motion` first after changing packages/motion; the prototype build runs this.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = dirname(fileURLToPath(import.meta.url));
const bundle = readFileSync(resolve(dir, '../../../packages/motion/dist/landing-motion.js'), 'utf8');
const out = `/* Generated by scripts/motion.mjs from packages/motion/dist/landing-motion.js. Do not edit. */\n${bundle}`;
writeFileSync(resolve(dir, '../src/motion.js'), out);
console.log(`src/motion.js: ${Math.round(out.length / 1024)} KB`);
