// Copies the exercise animations the prototype uses (the `anim` and `easier` ids in src/core.js) from
// packages/motion/svg into src/motion.js as data URIs, so the prototype keeps working with no build step.
// Run after `pnpm --filter @landing/motion build`; the prototype build runs it too.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = dirname(fileURLToPath(import.meta.url));
const core = readFileSync(resolve(dir, '../src/core.js'), 'utf8');
const ids = [...new Set([...core.matchAll(/(?:anim|easier): '([a-z]+-\d)'/g)].map((m) => m[1]))].sort();
const lib = resolve(dir, '../../../packages/motion/svg');
const uri = (file) => 'data:image/svg+xml,' + encodeURIComponent(readFileSync(file, 'utf8')).replace(/%20/g, ' ').replace(/%3D/g, '=').replace(/%3A/g, ':').replace(/%2F/g, '/').replace(/'/g, '%27');
const loops = {}, stills = {};
for (const id of ids) {
  loops[id] = uri(resolve(lib, `${id}.svg`));
  stills[id] = uri(resolve(lib, 'still', `${id}.svg`));
}
const out = `/* Generated by scripts/motion.mjs from packages/motion/svg. Do not edit. */
window.LANDING_MOTION = ${JSON.stringify({ loops, stills })};
`;
writeFileSync(resolve(dir, '../src/motion.js'), out);
console.log(`src/motion.js: ${ids.length} animations, ${Math.round(out.length / 1024)} KB`);
